//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snet.Windows.PerformanceTesting {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snet.Windows.PerformanceTesting.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [ Snet.cn ] 性能测试 的本地化字符串。
        /// </summary>
        internal static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string 主题 {
            get {
                return ResourceManager.GetString("主题", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string 停止 {
            get {
                return ResourceManager.GetString("停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止发送 的本地化字符串。
        /// </summary>
        internal static string 停止发送 {
            get {
                return ResourceManager.GetString("停止发送", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止循环发送 的本地化字符串。
        /// </summary>
        internal static string 停止循环发送 {
            get {
                return ResourceManager.GetString("停止循环发送", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前缀 的本地化字符串。
        /// </summary>
        internal static string 前缀 {
            get {
                return ResourceManager.GetString("前缀", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string 发送 {
            get {
                return ResourceManager.GetString("发送", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string 启动 {
            get {
                return ResourceManager.GetString("启动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string 地址 {
            get {
                return ResourceManager.GetString("地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环发送 的本地化字符串。
        /// </summary>
        internal static string 循环发送 {
            get {
                return ResourceManager.GetString("循环发送", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环次数设置 的本地化字符串。
        /// </summary>
        internal static string 循环次数设置 {
            get {
                return ResourceManager.GetString("循环次数设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型 的本地化字符串。
        /// </summary>
        internal static string 数据类型 {
            get {
                return ResourceManager.GetString("数据类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        internal static string 数量 {
            get {
                return ResourceManager.GetString("数量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志信息 的本地化字符串。
        /// </summary>
        internal static string 日志信息 {
            get {
                return ResourceManager.GetString("日志信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务地址设置 的本地化字符串。
        /// </summary>
        internal static string 服务地址设置 {
            get {
                return ResourceManager.GetString("服务地址设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次数 的本地化字符串。
        /// </summary>
        internal static string 次数 {
            get {
                return ResourceManager.GetString("次数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string 清空 {
            get {
                return ResourceManager.GetString("清空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位数据设置 的本地化字符串。
        /// </summary>
        internal static string 点位数据设置 {
            get {
                return ResourceManager.GetString("点位数据设置", resourceCulture);
            }
        }
    }
}
